build_backend:
  extends:
    - .auth_gcp
    - .build_docker
  needs:
    - job: create_timestamp
      artifacts: true
  variables:
    ARCH: amd64
    IMAGE: ${BACKEND_IMAGE}
    DOCKERFILE: deployment/Dockerfile.backend
    CONTEXT: .

build_web:
  extends:
    - .auth_gcp
    - .build_docker
  needs:
    - job: create_timestamp
      artifacts: true
  variables:
    ARCH: amd64
    IMAGE: ${WEB_IMAGE}
    DOCKERFILE: deployment/Dockerfile.web
    CONTEXT: .
    DOCKER_BUILD_ARGS: VITE_API_URL VITE_ESPLORA_BASE_URL VITE_NETWORK VITE_WATERFALLS_URL VITE_WATERFALLS_RECIPIENT VITE_DEBUG_MNEMONIC VITE_SIDESWAP_WS_URL VITE_DEMO_MODE VITE_GA_MEASUREMENT_ID VITE_PUBLIC_URL
    DEFAULT_BUILD_ARGS: >-
      VITE_API_URL=/api
      VITE_ESPLORA_BASE_URL=https://blockstream.info/liquidtestnet
      VITE_NETWORK=liquidtestnet
      VITE_WATERFALLS_URL=https://waterfalls-elements-testnet.esplora.staging.blockstream.io:17771
      VITE_WATERFALLS_RECIPIENT=age1ajng86w5g0qleku0k7eqjre5l7e6qaynjrnlyuc08w3ddu0etdcs379rr3
      VITE_SIDESWAP_WS_URL=wss://api-testnet.sideswap.io/server-connect
      VITE_GA_MEASUREMENT_ID=G-CPMC9XLYJ
      VITE_PUBLIC_URL=https://lending.dev.blockstream.com
    REQUIRED_BUILD_ARGS: VITE_API_URL VITE_ESPLORA_BASE_URL VITE_NETWORK VITE_WATERFALLS_URL
